document.getElementsByClassName("SecondHeading")[0].innerHTML = "By SHARMA JAYESH Ruplalji";
document.getElementsByClassName("SecondHeading")[0].style.color = "red";

let box1 = document.getElementsByClassName("box")[0];
box1.innerHTML = "This is box 1";
box1.style.backgroundColor = "lightblue";
box1.style.color = "white";
box1.style.padding = "20px";
box1.style.margin = "10px";
box1.style.fontSize = "20px";
box1.style.textAlign = "center";
box1.addEventListener("mouseover", ()=> {
    box1.style.backgroundColor = "blue";
});

    backgroundColor: "lightgreen",
document.getElementsByClassName("box")[1].style.backgroundColor = "lightgreen";
document.getElementsByClassName("box")[1].style.color = "white";
document.getElementsByClassName("box")[1].style.padding = "20px";
document.getElementsByClassName("box")[1].style.margin = "10px";
document.getElementsByClassName("box")[1].style.fontSize = "20px";
document.getElementsByClassName("box")[1].style.textAlign = "center";
    backgroundColor: "red",
document.getElementsByClassName("box")[2].style.backgroundColor = "red";
document.getElementsByClassName("box")[2].style.color = "white";
document.getElementsByClassName("box")[2].style.padding = "20px";
document.getElementsByClassName("box")[2].style.margin = "10px";
document.getElementsByClassName("box")[2].style.fontSize = "20px";
document.getElementsByClassName("box")[2].style.textAlign = "center";